apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: andrest-tap-node-example
  namespace: default
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: andrest-tap-node-example
spec:
  source:
    git:
      ref:
        branch: main
      url: https://github.com/sample-accelerators/andrest-tap-node-example.git
