apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: andrest-tap-node-example
  namespace: my-apps
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    app.kubernetes.io/part-of: andrest-tap-node-example
spec:
  source:
    git:
      ref:
        branch: main
      url: https://github.com/elfotografo007/andrest-tap-node-example.git
